// File generated by Antigravity based on existing Firebase project configuration.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// [FirebaseOptions] for the staging flavor.
class StagingFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'StagingFirebaseOptions have not been configured for web',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'StagingFirebaseOptions have not been configured for macos',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'StagingFirebaseOptions have not been configured for windows',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'StagingFirebaseOptions have not been configured for linux',
        );
      default:
        throw UnsupportedError(
          'StagingFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS4sFkbeI8P--sa4v4fKyjSukJ2Srb4Hk',
    appId: '1:995321223544:android:2a4f4e53ea3fafc31cd08d',
    messagingSenderId: '995321223544',
    projectId: 'investr-13bc4',
    storageBucket: 'investr-13bc4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpoMjBFAcgsNlTg7G7OHtZmkFPDnS4c0Q',
    appId: '1:995321223544:ios:ca484846d33c7c201cd08d',
    messagingSenderId: '995321223544',
    projectId: 'investr-13bc4',
    storageBucket: 'investr-13bc4.firebasestorage.app',
    iosBundleId: 'x.sohaibahmed.investr.staging',
  );
}
